version: "3"

volumes:
  web-static:
  postgres-data:

services:
  data:
    image: ubuntu
    volumes:
      - postgres-data:/data/postgres
    command: "true"

  web:
    restart: always
    build: ./web
    expose:
      - "8000"
    links:
      - postgres:postgres
    volumes:
      - web-static:/usr/src/app/bitsbox/bitsbox/static
    env_file: .env
    command: /usr/local/bin/gunicorn -w 2 -b :8000 app:app

  nginx:
    restart: always
    build: ./nginx
    ports:
      - "80:80"
    volumes:
      - web-static:/www/static
    links:
      - web:web

  postgres:
    restart: always
    image: postgres:latest
    volumes:
      - postgres-data:/var/lib/postgresql
    env_file: .env
    ports:
      - "5432:5432"
