"""empty message

Revision ID: 6e78e3e4b1a3
Revises: 
Create Date: 2017-01-25 21:09:35.598610

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import bitsbox.model

# revision identifiers, used by Alembic.
revision = '6e78e3e4b1a3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('layouts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Unicode(), nullable=False),
    sa.Column('spec', bitsbox.model.JSONEncodedDict(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('cabinets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Unicode(), nullable=False),
    sa.Column('layout_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['layout_id'], ['layouts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('layout_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('spec_item_path', bitsbox.model.JSONEncodedDict(), nullable=False),
    sa.Column('layout_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['layout_id'], ['layouts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cabinet_id', sa.Integer(), nullable=False),
    sa.Column('layout_item_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cabinet_id'], ['cabinets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['layout_item_id'], ['layout_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('drawers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.Unicode(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('collections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Unicode(), nullable=False),
    sa.Column('description', sa.Unicode(), nullable=False),
    sa.Column('content_count', sa.Integer(), nullable=True),
    sa.Column('drawer_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['drawer_id'], ['drawers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('resource_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Unicode(), nullable=False),
    sa.Column('collection_id', sa.Integer(), nullable=False),
    sa.Column('url', sqlalchemy_utils.types.url.URLType(), nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['collections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('resource_links')
    op.drop_table('collections')
    op.drop_table('drawers')
    op.drop_table('locations')
    op.drop_table('layout_items')
    op.drop_table('cabinets')
    op.drop_table('layouts')
    # ### end Alembic commands ###
